"use strict";

var conversions = [
  // AREA, SIbase = m2.
  {"unit" : "mm2",    "symbol" : "mm²", "toSIbase" : 0.000001,          "system" : "sMetric", "tag" : [], "category" : "cArea"},
  {"unit" : "cm2",    "symbol" : "cm²", "toSIbase" : 0.0001,            "system" : "sMetric", "tag" : [], "category" : "cArea"},
  {"unit" : "m2",     "symbol" : "m²",  "toSIbase" : 1,                 "system" : "sMetric", "tag" : [], "category" : "cArea"},
  {"unit" : "a",      "symbol" : "a",   "toSIbase" : 100,               "system" : "sMetric", "tag" : [], "category" : "cArea"},
  {"unit" : "ha",     "symbol" : "ha",  "toSIbase" : 10000,             "system" : "sMetric", "tag" : [], "category" : "cArea"},
  {"unit" : "km2",    "symbol" : "km²", "toSIbase" : 1000000,           "system" : "sMetric", "tag" : [], "category" : "cArea"},
  {"unit" : "in2",    "symbol" : "in²", "toSIbase" : 0.00064516,        "system" : "sIntl",   "tag" : [], "category" : "cArea"},
  {"unit" : "ft2",    "symbol" : "ft²", "toSIbase" : 0.092903,          "system" : "sIntl",   "tag" : [], "category" : "cArea"},
  {"unit" : "yd2",    "symbol" : "yd²", "toSIbase" : 0.836127,          "system" : "sIntl",   "tag" : [], "category" : "cArea"},
  {"unit" : "ac",     "symbol" : "ac",  "toSIbase" : 4046.8564224,      "system" : "sIntl",   "tag" : [], "category" : "cArea"},
  {"unit" : "mi2",    "symbol" : "mi²", "toSIbase" : 2589988.110336,    "system" : "sIntl",   "tag" : [], "category" : "cArea"},
  {"unit" : "tsh",    "symbol" : "T",   "toSIbase" : 93239571.972096,   "system" : "sUSC",    "tag" : [], "category" : "cArea"},

  // ENERGY, SIbase = J.
  {"unit" : "J",      "symbol" : "J",      "toSIbase" : 1,                 "system" : "sMetric", "tag" : [], "category" : "cEnergy"},
  {"unit" : "gcal",   "symbol" : "cal",    "toSIbase" : 4.184,             "system" : "sMetric", "tag" : [], "category" : "cEnergy"},
  {"unit" : "kJ",     "symbol" : "kJ",     "toSIbase" : 1000,              "system" : "sMetric", "tag" : [], "category" : "cEnergy"},
  {"unit" : "kcal",   "symbol" : "kcal",   "toSIbase" : 4184,              "system" : "sMetric", "tag" : [], "category" : "cEnergy"},
  {"unit" : "Wh",     "symbol" : "Wh",     "toSIbase" : 3600,              "system" : "sMetric", "tag" : [], "category" : "cEnergy"},
  {"unit" : "kWh",    "symbol" : "kWh",    "toSIbase" : 3600000,           "system" : "sMetric", "tag" : [], "category" : "cEnergy"},
  {"unit" : "ftlb",   "symbol" : "ft⋅lbf", "toSIbase" : 1.3558179483,      "system" : "sIntl",   "tag" : [], "category" : "cEnergy"},

  // FORCE, SIbase = N.
  {"unit" : "dyn",    "symbol" : "dyn",   "toSIbase" : 0.00001,           "system" : "sMetric", "tag" : [], "category" : "cForce"},
  {"unit" : "N",      "symbol" : "N",     "toSIbase" : 1,                 "system" : "sMetric", "tag" : [], "category" : "cForce"},
  {"unit" : "kN",     "symbol" : "kN",    "toSIbase" : 1000,              "system" : "sMetric", "tag" : [], "category" : "cForce"},
  {"unit" : "kgf",    "symbol" : "kgf",   "toSIbase" : 9.80665,           "system" : "sMetric", "tag" : [], "category" : "cForce"},
  {"unit" : "pdl",    "symbol" : "pdl",   "toSIbase" : 0.138254954376,    "system" : "sIntl",   "tag" : [], "category" : "cForce"},
  {"unit" : "lbf",    "symbol" : "lbf",   "toSIbase" : 4.4482216152605,   "system" : "sIntl",   "tag" : [], "category" : "cForce"},
  {"unit" : "kip",    "symbol" : "kip",   "toSIbase" : 4448.2216152605,   "system" : "sUSC",    "tag" : [], "category" : "cForce"},

  // LENGTH, SIbase = m.
  {"unit" : "nm",     "symbol" : "nm",    "toSIbase" : 0.000000001,       "system" : "sMetric", "tag" : [], "category" : "cLength"},
  {"unit" : "mcm",    "symbol" : "μm",    "toSIbase" : 0.000001,          "system" : "sMetric", "tag" : [], "category" : "cLength"},
  {"unit" : "mm",     "symbol" : "mm",    "toSIbase" : 0.001,             "system" : "sMetric", "tag" : [], "category" : "cLength"},
  {"unit" : "cm",     "symbol" : "cm",    "toSIbase" : 0.01,              "system" : "sMetric", "tag" : [], "category" : "cLength"},
  {"unit" : "dm",     "symbol" : "dm",    "toSIbase" : 0.1,               "system" : "sMetric", "tag" : [], "category" : "cLength"},
  {"unit" : "m",      "symbol" : "m",     "toSIbase" : 1,                 "system" : "sMetric", "tag" : [], "category" : "cLength"},
  {"unit" : "km",     "symbol" : "km",    "toSIbase" : 1000,              "system" : "sMetric", "tag" : [], "category" : "cLength"},
  {"unit" : "th",     "symbol" : "thou",  "toSIbase" : 0.0000254,         "system" : "sIntl",   "tag" : [], "category" : "cLength"},
  {"unit" : "in",     "symbol" : "in",    "toSIbase" : 0.0254,            "system" : "sIntl",   "tag" : [], "category" : "cLength"},
  {"unit" : "ft",     "symbol" : "ft",    "toSIbase" : 0.3048,            "system" : "sIntl",   "tag" : [], "category" : "cLength"},
  {"unit" : "yd",     "symbol" : "yd",    "toSIbase" : 0.9144,            "system" : "sIntl",   "tag" : [], "category" : "cLength"},
  {"unit" : "ftm",    "symbol" : "ftm",   "toSIbase" : 1.8288,            "system" : "sIntl",   "tag" : [], "category" : "cLength"},
  {"unit" : "ch",     "symbol" : "ch",    "toSIbase" : 20.1168,           "system" : "sIntl",   "tag" : [], "category" : "cLength"},
  {"unit" : "fur",    "symbol" : "fur",   "toSIbase" : 201.168,           "system" : "sIntl",   "tag" : [], "category" : "cLength"},
  {"unit" : "mi",     "symbol" : "mi",    "toSIbase" : 1609.34,           "system" : "sIntl",   "tag" : [], "category" : "cLength"},
  {"unit" : "cb",     "symbol" : "cb",    "toSIbase" : 185.2,             "system" : "sNautical",      "tag" : [], "category" : "cLength"},
  {"unit" : "nmi",    "symbol" : "NM",    "toSIbase" : 1852,              "system" : "sNautical",      "tag" : [], "category" : "cLength"},
  {"unit" : "nl",     "symbol" : "NL",    "toSIbase" : 5556,              "system" : "sNautical",      "tag" : [], "category" : "cLength"},
  {"unit" : "au",     "symbol" : "au",    "toSIbase" : 149597870700,      "system" : "sAstronomical",  "tag" : [], "category" : "cLength"},
  {"unit" : "ly",     "symbol" : "ly",    "toSIbase" : 9460730472580800,  "system" : "sAstronomical",  "tag" : [], "category" : "cLength"},
  {"unit" : "pc",     "symbol" : "pc",    "toSIbase" : 30856775812799588, "system" : "sAstronomical",  "tag" : [], "category" : "cLength"},

  // MASS, SIbase = kg.
  {"unit" : "mg",     "symbol" : "mg",     "toSIbase" : 0.000001,          "system" : "sMetric",   "tag" : [],            "category" : "cMass"},
  {"unit" : "g",      "symbol" : "g",      "toSIbase" : 0.001,             "system" : "sMetric",   "tag" : [],            "category" : "cMass"},
  {"unit" : "hg",     "symbol" : "hg",     "toSIbase" : 0.01,              "system" : "sMetric",   "tag" : [],            "category" : "cMass"},
  {"unit" : "kg",     "symbol" : "kg",     "toSIbase" : 1,                 "system" : "sMetric",   "tag" : [],            "category" : "cMass"},
  {"unit" : "t",      "symbol" : "t",      "toSIbase" : 1000,              "system" : "sMetric",   "tag" : ["tMetric"],   "category" : "cMass"},
  {"unit" : "gr",     "symbol" : "gr",     "toSIbase" : 0.00006479891,     "system" : "sIntl",     "tag" : [],            "category" : "cMass"},
  {"unit" : "ct",     "symbol" : "ct",     "toSIbase" : 0.0002,            "system" : "sIntl",    "tag" : [],            "category" : "cMass"},
  {"unit" : "dwt",    "symbol" : "dwt",    "toSIbase" : 0.00155517384,     "system" : "sIntl",     "tag" : [],            "category" : "cMass"},
  {"unit" : "oz",     "symbol" : "oz",     "toSIbase" : 0.028349523125,    "system" : "sIntl",     "tag" : [],            "category" : "cMass"},
  {"unit" : "ozt",    "symbol" : "oz t",   "toSIbase" : 0.0311034768,      "system" : "sIntl",     "tag" : [],            "category" : "cMass"},
  {"unit" : "lbt",    "symbol" : "lb t",   "toSIbase" : 0.3732417216,      "system" : "sIntl",     "tag" : [],            "category" : "cMass"},
  {"unit" : "lb",     "symbol" : "lb",     "toSIbase" : 0.45359237,        "system" : "sIntl",     "tag" : [],            "category" : "cMass"},
  {"unit" : "st",     "symbol" : "st",     "toSIbase" : 6.35029,           "system" : "sIntl",     "tag" : [],            "category" : "cMass"},
  {"unit" : "cwtUK",  "symbol" : "cwt",    "toSIbase" : 50.80234544,       "system" : "sImperial", "tag" : ["tImperial"], "category" : "cMass"},
  {"unit" : "tonUK",  "symbol" : "",       "toSIbase" : 1016.047,          "system" : "sImperial", "tag" : ["tImperial"], "category" : "cMass"},
  {"unit" : "cwtUS",  "symbol" : "cwt",    "toSIbase" : 45.35923700,       "system" : "sUSC",      "tag" : ["tUS"],       "category" : "cMass"},
  {"unit" : "tonUS",  "symbol" : "",       "toSIbase" : 907.1847,          "system" : "sUSC",      "tag" : ["tUS"],       "category" : "cMass"},

  // PRESSURE, SIbase = Pa.
  {"unit" : "Pa",     "symbol" : "Pa",     "toSIbase" : 1,                 "system" : "sMetric", "tag" : [], "category" : "cPressure"},
  {"unit" : "kPa",    "symbol" : "kPa",    "toSIbase" : 1000,              "system" : "sMetric", "tag" : [], "category" : "cPressure"},
  {"unit" : "bar",    "symbol" : "bar",    "toSIbase" : 100000,            "system" : "sMetric", "tag" : [], "category" : "cPressure"},
  {"unit" : "psi",    "symbol" : "psi",    "toSIbase" : 6894.7572932,      "system" : "sIntl",   "tag" : [], "category" : "cPressure"},
  {"unit" : "cmH2O",  "symbol" : "cmH₂O",  "toSIbase" : 98.0665,           "system" : "sOther",  "tag" : [], "category" : "cPressure"},
  {"unit" : "torr",   "symbol" : "Torr",   "toSIbase" : 133.32236842,      "system" : "sOther",  "tag" : [], "category" : "cPressure"},
  {"unit" : "mmHg",   "symbol" : "mm Hg",  "toSIbase" : 133.322387415,     "system" : "sOther",  "tag" : [], "category" : "cPressure"},
  {"unit" : "inH2O",  "symbol" : "inH₂O",  "toSIbase" : 248.843,           "system" : "sOther",  "tag" : [], "category" : "cPressure"},
  {"unit" : "inHg",   "symbol" : "inHg",   "toSIbase" : 3386.389,          "system" : "sOther",  "tag" : [], "category" : "cPressure"},
  {"unit" : "atm",    "symbol" : "atm",    "toSIbase" : 101325,            "system" : "sOther",  "tag" : [], "category" : "cPressure"},

  // SPEED, SIbase = km/h.
  {"unit" : "kmph",   "symbol" : "km/h",   "toSIbase" : 1,                 "system" : "sMetric",   "tag" : [], "category" : "cSpeed"},
  {"unit" : "mps",    "symbol" : "m/s",    "toSIbase" : 3.6,               "system" : "sMetric",   "tag" : [], "category" : "cSpeed"},
  {"unit" : "ips",    "symbol" : "ips",    "toSIbase" : 0.09144,           "system" : "sIntl",     "tag" : [], "category" : "cSpeed"},
  {"unit" : "fps",    "symbol" : "ft/s",   "toSIbase" : 1.09728,           "system" : "sIntl",     "tag" : [], "category" : "cSpeed"},
  {"unit" : "mph",    "symbol" : "mph",    "toSIbase" : 1.60934,           "system" : "sIntl",     "tag" : [], "category" : "cSpeed"},
  {"unit" : "kt",     "symbol" : "kn",     "toSIbase" : 1.852,             "system" : "sNautical", "tag" : [], "category" : "cSpeed"},
  {"unit" : "sol",    "symbol" : "c",      "toSIbase" : 1079252848.8,      "system" : "sOther",    "tag" : [], "category" : "cSpeed"},

  // TEMPERATURE, SIbase = C.
  {"unit" : "K",      "symbol" : "K",      "toSIbase" : 1,     "addToSIbase": 273.15, "allowZero": true, "system": "sMetric", "tag" : [], "category" : "cTemperature"},
  {"unit" : "C",      "symbol" : "°C",     "toSIbase" : 1,     "addToSIbase": 0,      "allowZero": true, "system": "sMetric", "tag" : [], "category" : "cTemperature"},
  {"unit" : "F",      "symbol" : "°F",     "toSIbase" : 5/9,   "addToSIbase": 32,     "allowZero": true, "system": "sUSC",    "tag" : [], "category" : "cTemperature"},
  {"unit" : "Ra",     "symbol" : "°Ra",    "toSIbase" : 5/9,   "addToSIbase": 491.67, "allowZero": true, "system": "sOther",  "tag" : [], "category" : "cTemperature"},
  {"unit" : "Re",     "symbol" : "°Ré",    "toSIbase" : 1.25,  "addToSIbase": 0,      "allowZero": true, "system": "sOther",  "tag" : [], "category" : "cTemperature"},
  {"unit" : "Ro",     "symbol" : "°Rø",    "toSIbase" : 40/21, "addToSIbase": 7.5,    "allowZero": true, "system": "sOther",  "tag" : [], "category" : "cTemperature"},

  // TIME, SIbase = sec.
  {"unit" : "ms",     "symbol" : "ms",     "toSIbase" : 0.001,             "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "sec",    "symbol" : "s",      "toSIbase" : 1,                 "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "min",    "symbol" : "min",    "toSIbase" : 60,                "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "hour",   "symbol" : "h",      "toSIbase" : 3600,              "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "day",    "symbol" : "d",      "toSIbase" : 86400,             "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "week",   "symbol" : "",       "toSIbase" : 604800,            "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "month",  "symbol" : "",       "toSIbase" : 2629800,           "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "year",   "symbol" : "",       "toSIbase" : 31557600,          "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "decad",  "symbol" : "",       "toSIbase" : 315576000,         "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "centu",  "symbol" : "",       "toSIbase" : 3155760000,        "system" : "sMetric",   "tag" : [], "category" : "cTime"},
  {"unit" : "mille",  "symbol" : "",       "toSIbase" : 31557600000,       "system" : "sMetric",   "tag" : [], "category" : "cTime"},

  // VOLUME, SIbase = l.
  {"unit" : "ml",     "symbol" : "ml",     "toSIbase" : 0.001,             "system" : "sMetric", "tag" : [],            "category" : "cVolume"},
  {"unit" : "tsp",    "symbol" : "",       "toSIbase" : 0.005,             "system" : "sMetric", "tag" : ["tMetric"],   "category" : "cVolume"},
  {"unit" : "cl",     "symbol" : "cl",     "toSIbase" : 0.01,              "system" : "sMetric", "tag" : [],            "category" : "cVolume"},
  {"unit" : "tbsp",   "symbol" : "",       "toSIbase" : 0.015,             "system" : "sMetric", "tag" : ["tMetric"],   "category" : "cVolume"},
  {"unit" : "dl",     "symbol" : "dl",     "toSIbase" : 0.1,               "system" : "sMetric", "tag" : [],            "category" : "cVolume"},
  {"unit" : "l",      "symbol" : "l",      "toSIbase" : 1,                 "system" : "sMetric", "tag" : [],            "category" : "cVolume"},
  {"unit" : "m3",     "symbol" : "m³",     "toSIbase" : 1000,              "system" : "sMetric", "tag" : [],            "category" : "cVolume"},
  {"unit" : "in3",    "symbol" : "in³",    "toSIbase" : 0.016387064,       "system" : "sIntl",   "tag" : [],            "category" : "cVolume"},
  {"unit" : "ft3",    "symbol" : "ft³",    "toSIbase" : 28.316846592,      "system" : "sIntl",   "tag" : [],            "category" : "cVolume"},
  {"unit" : "yd3",    "symbol" : "yd³",    "toSIbase" : 764.554857984,     "system" : "sIntl",   "tag" : [],            "category" : "cVolume"},
  {"unit" : "acft",   "symbol" : "ac⋅ft",  "toSIbase" : 1233481.83754752,  "system" : "sIntl",   "tag" : [],            "category" : "cVolume"},
  {"unit" : "tspUK",  "symbol" : "",       "toSIbase" : 0.00591939,        "system" : "sImperial", "tag" : ["tImperial"], "category" : "cVolume"},
  {"unit" : "tbspUK", "symbol" : "",       "toSIbase" : 0.0177582,         "system" : "sImperial", "tag" : ["tImperial"], "category" : "cVolume"},
  {"unit" : "fOzUK",  "symbol" : "fl oz",  "toSIbase" : 0.0284130625,      "system" : "sImperial", "tag" : ["tImperial"], "category" : "cVolume"},
  {"unit" : "ptUK",   "symbol" : "pt",     "toSIbase" : 0.56826125,        "system" : "sImperial", "tag" : ["tImperial"], "category" : "cVolume"},
  {"unit" : "qtUK",   "symbol" : "qt",     "toSIbase" : 1.1365225,         "system" : "sImperial", "tag" : ["tImperial"], "category" : "cVolume"},
  {"unit" : "galUK",  "symbol" : "gal",    "toSIbase" : 4.54609,           "system" : "sImperial", "tag" : ["tImperial"], "category" : "cVolume"},
  {"unit" : "tspUS",  "symbol" : "",       "toSIbase" : 0.00492892,        "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "tbspUS", "symbol" : "",       "toSIbase" : 0.0147868,         "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "fOzUS",  "symbol" : "fl oz",  "toSIbase" : 0.0295735156,      "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "cupUS",  "symbol" : "",       "toSIbase" : 0.236588125,       "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "ptUS",   "symbol" : "pt",     "toSIbase" : 0.473176473,       "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "ptdUS",  "symbol" : "pt",     "toSIbase" : 0.5506104713575,   "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "qtUS",   "symbol" : "qt",     "toSIbase" : 0.946352946,       "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "qtdUS",  "symbol" : "qt",     "toSIbase" : 1.101220942715,    "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "potUS",  "symbol" : "pot",    "toSIbase" : 1.89270589,        "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "galUS",  "symbol" : "gal",    "toSIbase" : 3.78541,           "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
  {"unit" : "bbl",    "symbol" : "bbl",    "toSIbase" : 158.98722,         "system" : "sUSC",    "tag" : ["tUS"],       "category" : "cVolume"},
]
